all:
  hosts:
    batchvm1:
      host: 13.65.42.214
    batchvm2:
      host: 104.215.72.107
    batchvm3:
      host: 20.97.12.217
    # batchvm4:
    #   host: 13.84.166.27
    # batchvm5:
    #   host: 13.66.8.112

  vars:
    ansible_python_interpreter: /usr/bin/python3
    ansible_ssh_private_key_file: ~/.ssh/2105-may24-devops-ubuntu-vm-1_key.pem
    ansible_user: richard
